apiVersion: v1
kind: Secret
metadata:
  labels:
    app: acmefit
  name: order-postgres-pass
  namespace: default
data:
  password: S2VlcEl0U2ltcGxlMSE=
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: acmefit
  name: cart-redis-pass
  namespace: default
data:
  password: S2VlcEl0U2ltcGxlMSE=
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: acmefit
  name: catalog-mongo-pass
  namespace: default
data:
  password: S2VlcEl0U2ltcGxlMSE=
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: acmefit
  name: users-mongo-pass
  namespace: default
data:
  password: S2VlcEl0U2ltcGxlMSE=
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: acmefit
  name: users-redis-pass
  namespace: default
data:
  password: S2VlcEl0U2ltcGxlMSE=
type: Opaque
